name: Build & Test

on:
  push:
    branches: [ main ]

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.2"

      - run: opam install . --deps-only --with-test
      
      - name: Install opam pkgs
        run: opam install ocamlformat.0.26.2 ounit2

      - name: Dune Build
      - run: opam exec -- dune build

      - name: Run Tests
      - run: opam exec -- dune runtest

      - name: Format
      - run: opem exec -- dune fmt
